### ISSUE TITLE
 basis matrix type returned by different methods.

### ISSUE THREAD

**Issue by ccshao** [marinkaz/nimfa#17]
I found methods return basis / coefficient matrix  in different data type. 

For example, 
**pmf** and **nsnmf** (as far as I noticed) return basis matrix in ***sparse matrix of type '<type 'numpy.float64'***;

**bd**, **lfnmf** and **nmf** return basis matrix in ***matrix*** format. 

Could you kindly make the return matrix in same data type?

Thanks,

**Comment by marinkaz** [comment]
Fixed in 4d6a6951f06f45b445694d688a7653d94036d77d.
