### ISSUE TITLE
'module' object has no attribute 'Nmf'

### ISSUE THREAD

**Issue by a-peleteiro** [marinkaz/nimfa#18]
HI,

I am trying to use Nimfa to use the NMF. I have installed nimfa in the python interpreter and this is the part in my code.

import nimfa

nmf = nimfa.Nmf(tfidf, max_iter=200, rank=2, update='divergence', objective='div')
fit = nmf()
print("Residual sum of squares: ", fit.summary(None)['rss'])

However, I keep on getting this error

AttributeError: 'module' object has no attribute 'Nmf'

Am I doing something wrong?

Thank you

**Comment by marinkaz** [comment]
I tried to re-run your code and it completed successfully in both Python 2 and 3. Please check that you are using the latest version of Nimfa available from this repository.

**Comment by a-peleteiro** [comment]
Hi Marinkaz,

I have downloaded the package straight from the IDE I am using (PyCharm) and my interpreter is Python 2.7.6 MacOS. The version of nimfa is 1.1.

Thanks 
Ana

**Comment by marinkaz** [comment]
Nimfa has recently undergone a substantial change in the API. Please download and install the latest release from https://github.com/marinkaz/nimfa/releases/tag/v1.2.1. I suspect that you got an older version of nimfa from pip, where the call to NMF algorithm was entirely different.

**Comment by a-peleteiro** [comment]
Yes, that was the problem, it is working now.
Thanks a lot!
