### ISSUE TITLE
Default kwargs set incorrectly

### ISSUE THREAD

**Issue by d10genes** [marinkaz/nimfa#21]
In 539f0692 (see [here](https://github.com/marinkaz/nimfa/commit/539f0692ca81d998e70912c9bcba366a5d2c49ab#diff-1cb9db188ddd1d2bc5f359bc5030a762R189)) `is not None` was introduced to replace implicit boolean use (i.e., `not alpha`) on multiple models, but I believe the meaning was reversed and should be `is None` instead. Currently leaving the defaults as None doesn't set them to a default and leaves them as None, throwing errors on down the line.

**Comment by marinkaz** [comment]
There were issues with BD and SNMNMF. Fixed in f5847ccc24bd169cfdaa2f9ee199d9ebe892b1fb.
