### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Lsnmf'

### ISSUE THREAD

**Issue by xinzhige** [marinkaz/nimfa#24]
When I tried to test the example (Lsnmf) given by the official site of Nimfa, like:

import nimfa
V = nimfa.examples.medulloblastoma.read(normalize=True)
lsnmf = nimfa.Lsnmf(V, seed='random_vcol', rank=50, max_iter=100)

then I got the following error:

AttributeError: 'module' object has no attribute 'Lsnmf'

I guess the reason might be we need to give the whole path of Lsnmf like, nimfa.methods.factorization.lsnmf.Lsnmf. 

But when I did this, 

lsnmf = nimfa.methods.factorization.lsnmf.Lsnmf(V, seed='random_vcol', rank=50, max_iter=100), 

then it gave me:

TypeError: __init__() takes exactly 1 argument (5 given).

How can I solve this problem?

**Comment by singhketan** [comment]
How did you solve this? I'm having the same problem.

**Comment by marinkaz** [comment]
Please install the latest release of Nimfa. The api has changed in v1.2.
