### ISSUE TITLE
Release v1.2 on PyPI

### ISSUE THREAD

**Issue by scottclowe** [marinkaz/nimfa#26]
The latest version on PyPI is still version 1.1, despite v1.2 having been released 8 months ago. Could you update the PyPI release so it is up to date?

Since the API has changed completely and we are developing code to work with the latest version, we need to require v1.2 as a dependency for a package we (@swkeemink) are creating.

Thanks!

**Comment by marinkaz** [comment]
Thanks for a reminder! The PyPi release is updated.
