### ISSUE TITLE
'Mf_fit' object has no attribute 'estimate_rank'

### ISSUE THREAD

**Issue by wpoates1** [marinkaz/nimfa#30]
Really appreciating Nimfa and its working well for me in factorizing some preference data. I am however trying to test different ranks, and would like to use the built-in method to return quality parameter. I cannot get the estimate_rank method to work however. Sample code:

```
import numpy as np

import nimfa

V = np.array([[1, 2, 3], [4, 5, 6], [6, 7, 8]])
print('Target:\n%s' % V)

lsnmf = nimfa.Lsnmf(V, seed='random_vcol', max_iter=10, rank=3, track_error=True)
lsnmf_fit = lsnmf()

W = lsnmf_fit.basis()
print('Basis matrix:\n%s' % W)

H = lsnmf_fit.coef()
print('Mixture matrix:\n%s' % H)

r = lsnmf_fit.estimate_rank()
print('Rank estimate:\n%' % r)
```

Running Python 3.5 with Nimfa 1.2.2

Thankyou!

**Comment by wpoates1** [comment]
OK - I've worked this out. I think my python inexperience is showing here, or it could be a documentation issue? In any event, I now have the estimate_rank function working, by calling it using the "fit" object of my nmf object. If you see what I mean.

Thanks

**Comment by marinkaz** [comment]
Thanks for noting! An example on how to use the estimate_rank function is now included at http://nimfa.biolab.si
