### ISSUE TITLE
Options have no effect in factorization

### ISSUE THREAD

**Issue by yskangtamu** [marinkaz/nimfa#33]
Hello Marinka Zitnik, 

I have been using your `nimfa` module for my research. While comparing results from various `seeding` methods, I realized that the variant of the NNDSVD algorithm is not taken into effect by the `flag`. So, for example, in [`nmf.py`](https://github.com/marinkaz/nimfa/blob/11410473f2bae413c213c98bd9ae75db10d36420/nimfa/methods/factorization/nmf.py#L179),

```
self.W, self.H = self.seed.initialize(
               self.V, self.rank, self.options)
```
should be like
```
self.W, self.H = self.seed.initialize(
               self.V, self.rank, self.options['options'])
```
for the non-default NNDSVD algorithms, NNDSVDa or NNDSVDar, to be able to be in effect. As you already know, this applies to almost all the `py` files in the `factorization` directory.

Thank you,
yskangtamu

**Comment by marinkaz** [comment]
Hi yskangtamu, 

The appropriate way to use NNDSVDa (`flag=1`) or NNDSVDar (`flag=2`) algorithm is the following:
```
import nimfa
V = nimfa.examples.medulloblastoma.read(normalize=True)
lsnmf = nimfa.Lsnmf(V, seed='nndsvd', flag=1, rank=10, max_iter=100)
lsnmf_fit = lsnmf()
```

I assume your issue occurred because you ran factorization as:
```
lsnmf = nimfa.Lsnmf(V, seed='nndsvd', options={'flag':1}, rank=10, max_iter=100)
```
