### ISSUE TITLE
Gillis2014 paper does not corresponds to the 'xray' algorithm in SepNMF

### ISSUE THREAD

**Issue by liubenyuan** [marinkaz/nimfa#34]
Hi, thanks for this package.

I read gillis2014 paper entitled "Fast and Robust Recursive Algorithms for Separable Nonnegative Matrix Factorization" on IEEE PAMI. This article provides a `spa` alike algorithm, it does not give `xray`.

Where is this xray algorithm ? should the comment on sepnmf being updated.

Best.

**Comment by marinkaz** [comment]
@ismav, can you comment on this issue?

**Comment by ismav** [comment]
@marinkaz I believe in the comment we swapped XRAY with SPA. 
Is it possible to just swap to the correct order:

XRAY --- Kumar et al (2013) and SPA --- Gilles et al (2014).

**Comment by marinkaz** [comment]
Done. @ismav, thanks!
