### ISSUE TITLE
example datasets are no longer available

### ISSUE THREAD

**Issue by AssyaTrofimov** [marinkaz/nimfa#37]
Hi!
The datasets  (leukemia and medulloblastoma) located here are no longer available:
http://nimfa.biolab.si/nimfa.datasets.html

Is there a way to get them?

Thanks

**Comment by marinkaz** [comment]
Hi @AssyaTrofimov,

You are right. The leukemia and medulloblastoma datasets are currently unavailable to download from broadinstitute.org. 

The good news is that these two datasets (which are small in size) are actually included in nimfa. Please download nimfa from pypi (https://pypi.python.org/pypi/nimfa/1.3.2). The ALL/AML and medulloblastoma data are in  ``nimfa/datasets``.
