### ISSUE TITLE
Snmf factorization method version = 'l' problem when initilisation matrices W & H are provided 

### ISSUE THREAD

**Issue by WillFroom** [marinkaz/nimfa#38]
When the 'l' version of SNFM is chosen and initilisation matrices are provided the factorize method does not swap and transpose initial W and H as it says it should in lines 176-177, it instead just keeps them in their original state which results in a error in line 197 when the matrices can't be broadcasted together.

**Comment by marinkaz** [comment]
This is fixed now, thanks!
