### ISSUE TITLE
Python-mapping sometimes used as index

### ISSUE THREAD

**Issue by c-thiel** [marinkaz/nimfa#40]
I was just playing around with this awesome toolbox when I encountered an occasional IndexError in `snmf.py` line 565:
```python
t_d = D[l_1n, l_2n] / (D[l_1n, l_2n] - K[l_1n, l_2n])
```
I checked the code and found the problem in the `if`-statement above:
```                    
if n_h_set == 1:
    h_n = h_set * np.ones((1, len(j_f)))
    l_1n = i_f
    l_2n = map(int, h_n.tolist()[0])
else:
   l_1n = i_f
   l_2n = map(int, [h_set[e] for e in j_f])
```
In newer python versions a mapping can not be used as an index, hence indexing `D` with `l_2n` fails. A simple fix would be to put a `list()` around the mapping.

Thanks!

**Comment by marinkaz** [comment]
Fixed, thanks!
