### ISSUE TITLE
Numpy deprecation warning

### ISSUE THREAD

**Issue by andrescarrasco** [marinkaz/nimfa#41]
When running snmf() the following warning appears:

C:\Python27-64\lib\site-packages\numpy\matrixlib\defmatrix.py:318: VisibleDeprecationWarning: non integer (and non boolean) array-likes will not be accepted as indices in the future
  out = N.ndarray.__getitem__(self, index)

**Comment by NMRobert** [comment]
Hi, this deprecation is now a breaking change in current versions of numpy and needs to be fixed. I think the simplest way of fixing it might just be to change lines like:

` eX = X[idxX / X.shape[1], idxX % X.shape[1]]`
to
` eX = X[idxX // X.shape[1], idxX % X.shape[1]]`

but there might be a more correct way.

**Comment by marinkaz** [comment]
It should be fixed now, thanks!
