### ISSUE TITLE
Help - How to estimate Coef (as in the H matrix) from a pre-computed W (the base matrix)

### ISSUE THREAD

**Issue by LinkOne1A** [marinkaz/nimfa#43]
Hello;

I hope you can provide me with a hint to figure this out.

Assume we already have successfully computed X ~= W1 * H1, using SNMF.

Now, say we have an X2 and we want to use the same W1 (as above, the pre-computed W1) to get a new H that can best use the existing W to estimate X2. How would one do this? 

Do I just call:
```
 snmf = nimfa.Snmf(X2 , ..., W=W1 ...) 
 fit = snmf()
 H2 = fit.coef()
 The new estimated X2 ~= W1 * H2 

``` 
If my hunch is correct, then I think there is a problem, but I am not sure I am using NIMFA correctly, hence this question.

Thanks!

Regards;

**Comment by marinkaz** [comment]
Hi, 

It is possible to reuse an existing latent factor (i.e., W1) to initialize factorization of a second matrix (i.e., X2). Here is how it can be done: 

```
import numpy as np
import nimfa

X2 = np.random.rand(30, 20)

W1 = np.random.rand(30, 4)
init_H = np.random.rand(4, 20)

# Fixed initialization of latent matrices
snmf = nimfa.Snmf(X2, seed="fixed", W=W1, H=init_H, rank=4)
snmf_fit = snmf()

print("Euclidean distance: %5.3f" % snmf_fit.distance(metric="euclidean"))
print('Initialization type: %s' % snmf_fit.seeding)
print('Iterations: %d' % snmf_fit.n_iter)
```

In this example, W1 is used to initialize latent factor W. Note that only initialization phase of W is fixed, W will still change during model training. 

If you would like to keep W fixed throughout training and only optimize over the space of factors H, I suggest making a very simple change in the code. In particular, you want to (1) initialize W with a pre-trained factor, and (2) comment the line in snmf.py that calls the updating function for W.
